# -*- coding: utf-8 -*-
"""Boot Mistral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxQq256ocQffExXXCboLvYvSf7ID4BKJ

# Normalizar los datos

Importar las librerías


*   Pandas: se utiliza para manipulación y análisis de datos
*   NumPy: librería de Python se utiliza para operaciones matemáticas, arrays, etc.

*as pd* es el alias de la librería para no escribir más "código"

*StandardScaler* y *MinMaxScaler*
Son clases (plantillas) que crean objetos capaces de escalar/normalizar datos.

*SimpleImputer* rellena los valores vacíos (nulos) automáticamente
"""

!pip install pandas numpy scikit-learn -q

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.impute import SimpleImputer

"""Cargar el data set

*df.shape* te muestra las filas y columnas
"""

from google.colab import files
uploaded = files.upload()  # subí tu sales_data_sample.csv

df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
print("Shape original:", df.shape)

"""Eliminar columnas innecesarias"""

cols_drop = [
    'ORDERNUMBER', 'ORDERLINENUMBER', 'ORDERDATE',
    'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
    'ADDRESSLINE1', 'ADDRESSLINE2', 'POSTALCODE',
    'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'STATE'
]
df = df.drop(columns=cols_drop)

"""Imputar nulos"""

cols_cat = ['STATUS', 'PRODUCTLINE', 'COUNTRY', 'TERRITORY', 'DEALSIZE', 'CITY']
imputer = SimpleImputer(strategy='most_frequent')
df[cols_cat] = imputer.fit_transform(df[cols_cat])

"""Normalizar columnas numéricas"""

cols_num = ['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'MSRP']
scaler = MinMaxScaler()
df[cols_num] = scaler.fit_transform(df[cols_num])

"""Guardar CSV limpio"""

df.to_csv('sales_clean.csv', index=False)
print("✅ Dataset limpio guardado. Shape:", df.shape)
print(df.head())

files.download('sales_clean.csv')

"""# RAG + Chatbot

Instalar las dependencias/librerías

API 🗝
"""

!pip install langchain langchain-community langchain-mistralai \ chromadb sentence-transformers mistralai -q

import os
import pandas as pd
from google.colab import userdata
from langchain_core.documents import Document
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
print("✅ Importaciones listas")

"""Cargar el CSV limpio"""

# Cargar el CSV limpio
from google.colab import files
uploaded = files.upload()  # ← te va a abrir un botón para subir el archivo
df = pd.read_csv('sales_clean.csv')
print("✅ Cargado correctamente. Shape:", df.shape)

"""RAG necesita texto, no números — cada fila se convierte en una oración

*f"..."* permite meter variables dentro del texto con *{}*

Convertimos en texto por que *ChromaDB* y los *embedding* trabajan con texto, no con tablas numéricas
"""

def fila_a_texto(row):
    return (
        f"Venta: {row['PRODUCTLINE']} | País: {row['COUNTRY']} | "
        f"Ciudad: {row['CITY']} | Territorio: {row['TERRITORY']} | "
        f"Cantidad ordenada (norm): {row['QUANTITYORDERED']:.2f} | "
        f"Precio unitario (norm): {row['PRICEEACH']:.2f} | "
        f"Total venta (norm): {row['SALES']:.2f} | "
        f"MSRP (norm): {row['MSRP']:.2f} | "
        f"Tamaño del deal: {row['DEALSIZE']} | "
        f"Estado: {row['STATUS']} | "
        f"Trimestre: {row['QTR_ID']:.0f} | Mes: {row['MONTH_ID']:.0f} | Año: {row['YEAR_ID']:.0f}"
    )

documentos = [
    Document(page_content=fila_a_texto(row), metadata={"index": i})
    for i, row in df.iterrows()
]
print(f"✅ {len(documentos)} documentos creados")

"""Embedir"""

print("⏳ Creando embeddings (puede tardar 2-3 minutos)...")
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    # Modelo multilingüe: entiende preguntas en español e inglés
)

vectorstore = Chroma.from_documents(documentos, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 10})
print("✅ Vector store listo")

"""Configurar Mistral

*ChatMistralAI* crea la conexión con la API de MIstral usando la key que guardé en "Secrets"
"""

llm = ChatMistralAI(model="mistral-small-latest", temperature=0.1)

prompt_template = """
Eres un analista de ventas experto. Usa SOLO la información del contexto para responder.
Si no podés responder con los datos del contexto, decilo claramente.
Responde siempre en español.

Contexto:
{context}

Pregunta: {question}

Respuesta:
"""
prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])

def formatear_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

qa_chain = (
    {"context": retriever | formatear_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)
print("✅ Cadena RAG lista")

"""Chatbot"""

print("\n🤖 Chatbot listo. Escribí 'salir' para terminar.\n")

while True:
    pregunta = input("Vos: ")
    if pregunta.lower() in ['salir', 'exit', 'quit']:
        print("¡Hasta luego!")
        break
    if not pregunta.strip():
        continue
    respuesta = qa_chain.invoke(pregunta)
    print(f"\n🤖 Bot: {respuesta}\n")

"""Copia en git hub"""

!git clone https://github.com/miliacoss0/Boot-con-Mistral.ia.git

"""# Trabajar con el profesor, seguir en el mismo proyecto

Limpiar el dataset
"""

!pip install pandas numpy scikit-learn -q

"""Importaciones"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from google.colab import files

"""Cargar y limpiar el dataset"""

# Subir archivo
uploaded = files.upload()
df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
print("Shape original:", df.shape)

# Eliminar columnas inútiles
cols_drop = [
    'ORDERNUMBER', 'ORDERLINENUMBER', 'ORDERDATE',
    'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
    'ADDRESSLINE1', 'ADDRESSLINE2', 'POSTALCODE',
    'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'STATE'
]
df = df.drop(columns=cols_drop)

# Imputar nulos en columnas de texto
cols_cat = ['STATUS', 'PRODUCTLINE', 'COUNTRY', 'TERRITORY', 'DEALSIZE', 'CITY']
imputer = SimpleImputer(strategy='most_frequent')
df[cols_cat] = imputer.fit_transform(df[cols_cat])

# Normalizar columnas numéricas
cols_num = ['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'MSRP']
scaler = MinMaxScaler()
df[cols_num] = scaler.fit_transform(df[cols_num])

# Guardar y descargar
df.to_csv('sales_clean.csv', index=False)
files.download('sales_clean.csv')
print("✅ Dataset limpio. Shape:", df.shape)
print(df.head())

"""Instalar PandasIA"""

!pip install langchain langchain-community langchain-mistralai langchain-experimental -q

import os
import pandas as pd
from google.colab import userdata
from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents import create_pandas_dataframe_agent

os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
print("✅ Listo")

"""Cargar el dataset y crear el agente"""

# Cargar el dataset limpio
df = pd.read_csv('sales_clean.csv')
print("✅ Dataset cargado:", df.shape)

# Crear el LLM
llm = ChatMistralAI(model="mistral-small-latest", temperature=0)

# Crear el agente
agente = create_pandas_dataframe_agent(
    llm=llm,
    df=df,
    verbose=True,
    allow_dangerous_code=True,
    agent_executor_kwargs={"handle_parsing_errors": True}  # ← forma correcta
)

print("✅ Agente listo!")

"""Chat con el agente"""

print("\n🤖 Agente listo. Escribí 'salir' para terminar.\n")

while True:
    pregunta = input("Vos: ")
    if pregunta.lower() in ['salir', 'exit', 'quit']:
        print("¡Hasta luego!")
        break
    if not pregunta.strip():
        continue
    respuesta = agente.invoke(pregunta)
    print(f"\n🤖 Agente: {respuesta['output']}\n")

"""# Agregar el RAG

*-q* es para no mostrar tanto texto
"""

!pip install langchain langchain-core langchain-community langchain-mistralai chromadb sentence-transformers mistralai -q

"""Importaciones y la API 🗝"""

import os
import pandas as pd
from google.colab import userdata, files
from langchain_core.documents import Document
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

os.environ["MISTRAL_API_KEY"] = userdata.get('MISTRAL_API_KEY')
print("✅ Importaciones listas")

"""*   os → para guardar la API key como variable de entorno
*   Document → clase que representa cada texto del corpus
*   Chroma → base de datos vectorial donde se guardan los embeddings
*   HuggingFaceEmbeddings → convierte texto a vectores numéricos
*   ChatMistralAI → conexión con la API de Mistral
*   PromptTemplate → arma el mensaje que le mandás a Mistral
*   RunnablePassthrough → pasa la pregunta del usuario sin modificarla a través de la cadena
*   StrOutputParser → convierte la respuesta de Mistral a texto plano

Cargar el dataset y crear el corpus
"""

# Cargar el dataset limpio
uploaded = files.upload()
df = pd.read_csv('sales_clean.csv')
print("✅ Dataset cargado:", df.shape)


# CREAR EL CORPUS
# El corpus es la colección de textos que el RAG va a usar
# como base de conocimiento. Cada fila del dataset se convierte
# en un documento de texto descriptivo.

def fila_a_texto(row):
    return (
        f"Línea de producto: {row['PRODUCTLINE']} | "
        f"País: {row['COUNTRY']} | "
        f"Ciudad: {row['CITY']} | "
        f"Territorio: {row['TERRITORY']} | "
        f"Cantidad ordenada: {row['QUANTITYORDERED']:.2f} | "
        f"Precio unitario: {row['PRICEEACH']:.2f} | "
        f"Total venta: {row['SALES']:.2f} | "
        f"MSRP: {row['MSRP']:.2f} | "
        f"Tamaño del deal: {row['DEALSIZE']} | "
        f"Estado del pedido: {row['STATUS']} | "
        f"Trimestre: {row['QTR_ID']:.0f} | "
        f"Mes: {row['MONTH_ID']:.0f} | "
        f"Año: {row['YEAR_ID']:.0f}"
    )

# Crear el corpus — lista de documentos
corpus = [
    Document(page_content=fila_a_texto(row), metadata={"index": i})
    for i, row in df.iterrows()
]

print(f"✅ Corpus creado con {len(corpus)} documentos")
print(f"\nEjemplo de documento del corpus:")
print(corpus[0].page_content)

"""*.2f* --> sirve para mostrar números con dos decimales

Embeddings y Retriever
"""

# EMBEDDINGS Y RETRIEVER
# El retriever es el componente que busca en el corpus
# los documentos más relevantes para cada pregunta

print("⏳ Creando embeddings, esperá unos minutos...")

# Embeddings — convierte cada documento del corpus en un vector
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

# Vector store — guarda todos los vectores en ChromaDB
vectorstore = Chroma.from_documents(corpus, embeddings)

# Retriever — busca los 10 documentos más relevantes
# cuando recibe una pregunta
retriever = vectorstore.as_retriever(
    search_type="similarity",   # busca por similitud semántica
    search_kwargs={"k": 10}     # devuelve los 10 más similares
)

print("✅ Embeddings listos")
print("✅ Retriever configurado — busca los 10 documentos más similares")

"""* Toma los 2823 documentos del corpus, los convierte en vectores y los guarda en ChromaDB
* Es como crear una base de datos pero en vez de guardar texto, guarda vectores numéricos

Mistral, prefix, cadena RAG
"""

# ============================================================
# CONFIGURAR MISTRAL
# ============================================================
llm = ChatMistralAI(model="mistral-small-latest", temperature=0.1)
print("✅ Mistral configurado")

# PREFIX:

# El prefix son las instrucciones iniciales que le decís al
# agente cómo debe comportarse, qué rol tiene y qué límites
# tiene. Va al principio del prompt, antes del contexto.

prefix = """
Eres un agente experto en análisis de ventas con acceso a un
dataset de ventas internacionales. Tu trabajo es responder
preguntas sobre los datos de ventas de forma precisa y clara.

Reglas:
- Usá SOLO la información del contexto para responder
- Si no podés responder con los datos disponibles, decilo claramente
- Respondé siempre en español
- Sé conciso y directo en tus respuestas
- Si te preguntan por números, intentá dar valores aproximados basados en el contexto
"""


# PROMPT COMPLETO = PREFIX + CONTEXTO + PREGUNTA
prompt_template = prefix + """
Contexto del dataset:
{context}

Pregunta: {question}

Respuesta:
"""

prompt = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)
print("✅ Prefix y prompt configurados")

# CADENA RAG COMPLETA

def formatear_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context": retriever | formatear_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)
print("✅ Cadena RAG lista")

"""Chatbot RAG interactivo"""

# CHATBOT RAG INTERACTIVO

print("\n🤖 Chatbot RAG listo. Escribí 'salir' para terminar.")
print("\nEjemplos de preguntas:")
print("  - ¿Qué líneas de productos hay?")
print("  - ¿Qué países aparecen en los datos?")
print("  - ¿Cuál es el deal size más común?")
print("  - ¿Qué territorio tiene más ventas?\n")

while True:
    pregunta = input("Vos: ")
    if pregunta.lower() in ['salir', 'exit', 'quit']:
        print("¡Hasta luego!")
        break
    if not pregunta.strip():
        continue
    respuesta = rag_chain.invoke(pregunta)
    print(f"\n🤖 RAG: {respuesta}\n")