# -*- coding: utf-8 -*-
"""Tres agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSWg9eBdT_J5emSTZdArIMx9IM15oHQJ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print("Forma del dataset:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)
print("\nValores nulos por columnas:")
print(df.isnull().sum())

num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
imputer = SimpleImputer(strategy='mean')
df[num_cols] = imputer.fit_transform(df[num_cols])

print("Valores nulos luego de imputar:")
print(df.isnull().sum())

le = LabelEncoder()
df['placement_status'] = le.fit_transform(df['placement_status'])

print("Valores únicos después de codificar:")
print(df['placement_status'].value_counts())

features = [col for col in num_cols if col != 'placement_status']

scaler = StandardScaler()
df[features] = scaler.fit_transform(df[features])

print("Dataset escalado:")
print(df.head())

df.to_csv('dataset_limpio.csv', index=False)
print("Dataset normalizado guardado como dataset_limpio.csv")

df_limpio = pd.read_csv('dataset_limpio.csv')
print("Dataset limpio cargado:")
print(df_limpio.shape)
df_limpio.head()

X = df_limpio.drop(columns=['placement_status'])
y = df_limpio['placement_status']

print("Features (X):", X.shape)
print("Objetivo (Y):", y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Entrenamiento:", X_train.shape)
print("Prueba:", X_test.shape)

from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression(random_state=42)
modelo.fit(X_train, y_train)

print("Modelo entrenado")

from sklearn.metrics import accuracy_score, classification_report

y_pred = modelo.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte completo:")
print(classification_report(y_test, y_pred))