# -*- coding: utf-8 -*-
"""Tres agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSWg9eBdT_J5emSTZdArIMx9IM15oHQJ
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print("Forma del dataset:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)
print("\nValores nulos por columnas:")
print(df.isnull().sum())

num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
imputer = SimpleImputer(strategy='mean')
df[num_cols] = imputer.fit_transform(df[num_cols])

print("Valores nulos luego de imputar:")
print(df.isnull().sum())

le = LabelEncoder()
df['placement_status'] = le.fit_transform(df['placement_status'])

print("Valores únicos después de codificar:")
print(df['placement_status'].value_counts())

features = [col for col in num_cols if col != 'placement_status']

scaler = StandardScaler()
df[features] = scaler.fit_transform(df[features])

print("Dataset escalado:")
print(df.head())

df.to_csv('dataset_limpio.csv', index=False)
print("Dataset normalizado guardado como dataset_limpio.csv")